dist: trusty
sudo: required
services:
  - docker
language: node_js

node_js:
  - "10"
  - "9"
  - "8"

os:
  - linux

addons:
  apt:
    packages:
      - xvfb

before_install:
  - '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest' # skipped when using node 9
  - npm install -g greenkeeper-lockfile@1

before_script:
  - greenkeeper-lockfile-update

after_script:
  - greenkeeper-lockfile-upload

jobs:
  include:
    - stage: e2e
      node_js: "10"
      script: npm run test:e2e
